# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "ja-JP"
early_access: false

reviews:
  profile: "balanced"  # Options: strict, balanced, chill
  request_changes_workflow: false
  high_level_summary: true
  review_status: true
  collapse_walkthrough: false
  
  files:
    include:
      - "packages/flutter_whisper_kit/**/*.dart"
      - "packages/flutter_whisper_kit_apple/**/*.dart"
      - "packages/flutter_whisper_kit_apple/**/*.swift"
    exclude:
      - "**/.dart_tool/**"
      - "**/.flutter-plugins"
      - "**/.flutter-plugins-dependencies"
      - "**/.fvm/**"
      - "**/build/**"
      - "**/*.g.dart"  # Generated files

auto_review:
  enabled: true
  drafts: false
  bot_user_prs: true

chat:
  auto_reply: true
