name: workspace
publish_to: none 

environment:
  sdk: ^3.7.2

workspace:
  - packages/flutter_whisperkit
  - packages/flutter_whisperkit/example
  - packages/flutter_whisper_kit_apple
  - packages/flutter_whisper_kit_apple/example
