name: flutter_whisperkit_apple
description: "A Flutter plugin for WhisperKit on iOS and macOS platforms."
version: 0.0.1
homepage: https://github.com/r0227n/flutter_whisperkit

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  pigeon: ^22.7.0
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: FlutterWhisperkitApplePlugin
      macos:
        pluginClass: FlutterWhisperkitApplePlugin

pigeon:
  inputs:
    - pigeons/whisper_kit_api.dart
  dart_out: lib/src/whisper_kit_api.dart
  swift_out:
    - ios/flutter_whisperkit_apple/Sources/flutter_whisperkit_apple/WhisperKitApi.swift
    - macos/flutter_whisperkit_apple/Sources/flutter_whisperkit_apple/WhisperKitApi.swift
  swift_package_name: flutter_whisperkit_apple
