name: flutter_whisperkit_apple
description: "A new Flutter plugin project."
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: ^3.7.2
  flutter: '>=3.3.0'

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_whisperkit:
    path: ../flutter_whisperkit

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: FlutterWhisperkitApplePlugin
        swift_package_manager: true
      macos:
        pluginClass: FlutterWhisperkitApplePlugin
        swift_package_manager: true