name: flutter_whisperkit
description: "A Flutter plugin for WhisperKit speech recognition."
version: 0.0.1
homepage:

environment:
  sdk: ^3.7.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      ios:
        default_package: flutter_whisperkit_apple
      macos:
        default_package: flutter_whisperkit_apple
