name: flutter_whisper_kit_android
description: Android platform implementation for flutter_whisper_kit
version: 0.1.0
homepage: https://github.com/r0227n/flutter_whisper_kit
repository: https://github.com/r0227n/flutter_whisper_kit
issue_tracker: https://github.com/r0227n/flutter_whisper_kit/issues
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.3.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_whisper_kit:
    path: ../flutter_whisper_kit

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  yaml: ^3.1.2

flutter:
  plugin:
    platforms:
      android:
        package: com.r0227n.flutter_whisper_kit_android
        pluginClass: FlutterWhisperKitAndroidPlugin

topics:
  - audio
  - speech-recognition
  - whisper
  - android
