name: flutter_whisper_kit_android
description: Android platform implementation for flutter_whisper_kit
version: 0.1.0
homepage: https://github.com/r0227n/flutter_whisper_kit
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.3.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_whisper_kit:
    path: ../flutter_whisper_kit

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.0

flutter:
  plugin:
    platforms:
      android:
        package: com.r0227n.flutter_whisper_kit_android
        pluginClass: FlutterWhisperKitAndroidPlugin

topics:
  - audio
  - speech-recognition
  - whisper
  - android
