name: flutter_whisperkit_apple
description: "A Flutter plugin for WhisperKit speech recognition on Apple platforms."
version: 0.0.1
homepage:

environment:
  sdk: ^3.7.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_whisperkit:
    path: ../flutter_whisperkit
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.25.15

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: FlutterWhisperkitApplePlugin
      macos:
        pluginClass: FlutterWhisperkitApplePlugin
