name: 'Setup FVM'
description: 'Sets up Flutter Version Management (FVM) with the correct Flutter version'

outputs:
  flutter_version:
    description: "Flutter version from FVM config"
    value: ${{ steps.fvm_config.outputs.FLUTTER_VERSION }}

runs:
  using: "composite"
  steps:
    - name: Read FVM config
      id: fvm_config
      uses: kuhnroyal/flutter-fvm-config-action@v1
      shell: bash
    
    - name: Cache FVM
      uses: actions/cache@v3
      with:
        path: ~/.fvm
        key: ${{ runner.os }}-fvm-${{ steps.fvm_config.outputs.FLUTTER_VERSION }}
        restore-keys: |
          ${{ runner.os }}-fvm-
      shell: bash
    
    - name: Setup Flutter with FVM
      uses: leoafarias/fvm-action@v1
      with:
        version: ${{ steps.fvm_config.outputs.FLUTTER_VERSION }}
      shell: bash