// Autogenerated from Pigeon (v25.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class FLTWhisperKitConfig;
@class FLTTranscriptionResult;

@interface FLTWhisperKitConfig : NSObject
+ (instancetype)makeWithModelPath:(nullable NSString *)modelPath
    enableVAD:(nullable NSNumber *)enableVAD
    vadFallbackSilenceThreshold:(nullable NSNumber *)vadFallbackSilenceThreshold
    vadTemperature:(nullable NSNumber *)vadTemperature
    enableLanguageIdentification:(nullable NSNumber *)enableLanguageIdentification;
@property(nonatomic, copy, nullable) NSString * modelPath;
@property(nonatomic, strong, nullable) NSNumber * enableVAD;
@property(nonatomic, strong, nullable) NSNumber * vadFallbackSilenceThreshold;
@property(nonatomic, strong, nullable) NSNumber * vadTemperature;
@property(nonatomic, strong, nullable) NSNumber * enableLanguageIdentification;
@end

@interface FLTTranscriptionResult : NSObject
+ (instancetype)makeWithText:(nullable NSString *)text
    duration:(nullable NSNumber *)duration
    segments:(nullable NSArray<NSString *> *)segments
    language:(nullable NSString *)language;
@property(nonatomic, copy, nullable) NSString * text;
@property(nonatomic, strong, nullable) NSNumber * duration;
@property(nonatomic, copy, nullable) NSArray<NSString *> * segments;
@property(nonatomic, copy, nullable) NSString * language;
@end

/// The codec used by all APIs.
NSObject<FlutterMessageCodec> *FLTGetWhisperKitApiCodec(void);

@protocol FLTWhisperKitApi
/// @return `nil` only when `error != nil`.
- (nullable NSString *)getPlatformVersionWithError:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)initializeWhisperKitConfig:(FLTWhisperKitConfig *)config error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable FLTTranscriptionResult *)transcribeAudioFileFilePath:(NSString *)filePath error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)startStreamingTranscriptionWithError:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable FLTTranscriptionResult *)stopStreamingTranscriptionWithError:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable NSArray<NSString *> *)getAvailableModelsWithError:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void SetUpFLTWhisperKitApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FLTWhisperKitApi> *_Nullable api);

extern void SetUpFLTWhisperKitApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FLTWhisperKitApi> *_Nullable api, NSString *messageChannelSuffix);


@interface FLTWhisperKitEvents : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger messageChannelSuffix:(nullable NSString *)messageChannelSuffix;
- (void)onTranscriptionProgressProgress:(double)progress completion:(void (^)(FlutterError *_Nullable))completion;
- (void)onInterimTranscriptionResultResult:(FLTTranscriptionResult *)result completion:(void (^)(FlutterError *_Nullable))completion;
@end

NS_ASSUME_NONNULL_END
