name: Check Release

on:
  pull_request:
    branches:
      - 'release/**'

jobs:
  diff-files:
    name: Get Changed Files
    runs-on: ubuntu-latest
    outputs:
      pkg_apple: ${{ steps.changed-files.outputs.pkg_apple_any_changed == 'true' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46
        with:
          files_yaml: |
            pkg_apple:
              - 'packages/flutter_whisper_kit_apple/**'

  validate-apple-package-versions:
    name: Validate Apple Package Versions
    needs: diff-files
    if: ${{ needs.diff-files.outputs.pkg_apple }}
    uses: ./.github/workflows/wc-version-validation.yml
    with:
      pubspec_path: packages/flutter_whisper_kit_apple/pubspec.yaml
      podspec_path: packages/flutter_whisper_kit_apple/darwin/flutter_whisper_kit_apple.podspec

  sdk-compatibility:
    name: Run SDK Compatibility Tests
    uses: ./.github/workflows/wc-sdk-compatibility.yml
    permissions:
      pull-requests: write

