name: Check Release

on:
  pull_request:
    branches:
      - 'release/**'
      - 'develop'

permissions:
  pull-requests: write

jobs:
  validate-versions:
    name: Validate Package Versions
    if: contains(github.event.pull_request.changed_files, 'packages/flutter_whisper_kit_apple')
    uses: ./.github/workflows/wc-version-validation.yml
    with:
      pubspec_path: packages/flutter_whisper_kit_apple/pubspec.yaml
      podspec_path: packages/flutter_whisper_kit_apple/darwin/flutter_whisper_kit_apple.podspec

  sdk-compatibility:
    name: Run SDK Compatibility Tests
    uses: ./.github/workflows/wc-sdk-compatibility.yml
