name: Check Release

on:
  pull_request:
    branches:
      - 'release/**'
      - 'develop'

env:
  FLUTTER_WHISPER_KIT_APPLE_DIR: packages/flutter_whisper_kit_apple
  PUBSPEC_PATH: packages/flutter_whisper_kit_apple/pubspec.yaml
  PODSPEC_PATH: packages/flutter_whisper_kit_apple/darwin/flutter_whisper_kit_apple.podspec

jobs:
  validate-versions:
    name: Validate Package Versions
    if: contains(github.event.pull_request.changed_files, env.FLUTTER_WHISPER_KIT_APPLE_DIR)
    uses: ./.github/workflows/wc-version-validation.yml
    with:
      pubspec_path: ${{ env.PUBSPEC_PATH }}
      podspec_path: ${{ env.PODSPEC_PATH }}

  sdk-compatibility:
    name: Run SDK Compatibility Tests
    uses: ./.github/workflows/wc-sdk-compatibility.yml
