name: PR Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: check-pr-${{ github.ref }}
  cancel-in-progress: true

jobs:
  analyze-and-format:
    name: Dart Analysis and Format Check
    runs-on: ubuntu-24.04
    needs: check-file-changes
    if: needs.check-file-changes.outputs.dart_changed > 0

    steps:
      # https://github.com/actions/checkout
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Flutter
        uses: ./.github/actions/setup-flutter

      - name: Run melos analyze
        run: melos run analyze

      - name: Run melos test
        run: melos run test

      - name: Check melos format
        run: melos run ci:format

  check-file-changes:
    name: Check File Changes
    runs-on: ubuntu-24.04
    outputs:
      dart_changed: ${{ steps.check_changes.outputs.dart_changed }}
      yml_changed: ${{ steps.check_changes.outputs.yml_changed }}
      yaml_changed: ${{ steps.check_changes.outputs.yaml_changed }}
      md_changed: ${{ steps.check_changes.outputs.md_changed }}

    steps:
      # https://github.com/actions/checkout
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      # Check for file changes
      - name: Check for file changes
        id: check_changes
        uses: ./.github/actions/check-changes
        with:
          base_sha: ${{ github.event.pull_request.base.sha }}
          head_sha: ${{ github.event.pull_request.head.sha }}

  lint-yaml-markdown:
    name: Lint YAML and Markdown
    runs-on: ubuntu-24.04
    needs: check-file-changes
    if: needs.check-file-changes.outputs.yml_changed > 0 || needs.check-file-changes.outputs.yaml_changed > 0 || needs.check-file-changes.outputs.md_changed > 0

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Bun
        uses: ./.github/actions/setup-bun

      - name: Install dependencies
        run: bun install

      - name: Run Prettier check
        run: bun run ci:check
