name: Check Release

on:
  pull_request:
    branches:
      - 'release/**'
      
jobs:
  diff-files:
    name: Get Changed Files
    runs-on: ubuntu-latest
    outputs:
      pkg_apple: ${{ steps.changed-files.outputs.pkg_apple_any_changed }}
      pkg_flutter: ${{ steps.changed-files.outputs.pkg_flutter_any_changed }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46
        with:
          files_yaml: |
            pkg_flutter:
              - 'packages/flutter_whisper_kit/**'
            pkg_apple:
              - 'packages/flutter_whisper_kit_apple/**'

  validate-apple-package-versions:
    name: Validate Apple Package Versions
    needs: diff-files
    if: ${{ needs.diff-files.outputs.pkg_apple == 'true' }}
    uses: ./.github/workflows/wc-version-validation.yml
    with:
      pubspec_path: packages/flutter_whisper_kit_apple/pubspec.yaml
      podspec_path: packages/flutter_whisper_kit_apple/darwin/flutter_whisper_kit_apple.podspec

  sdk-compatibility:
    name: Run SDK Compatibility Tests
    uses: ./.github/workflows/wc-sdk-compatibility.yml
    permissions:
      pull-requests: write
      
  pana-evaluation-flutter:
    name: Run Pana Evaluation for Flutter Whisper Kit
    needs: diff-files
    if: ${{ needs.diff-files.outputs.pkg_flutter == 'true' }}
    uses: ./.github/workflows/wc-pana-evaluation.yml
    with:
      package_dir: packages/flutter_whisper_kit
    permissions:
      pull-requests: write
      
  pana-evaluation-apple:
    name: Run Pana Evaluation for Flutter Whisper Kit Apple
    needs: diff-files
    if: ${{ needs.diff-files.outputs.pkg_apple == 'true' }}
    uses: ./.github/workflows/wc-pana-evaluation.yml
    with:
      package_dir: packages/flutter_whisper_kit_apple
    permissions:
      pull-requests: write

