name: Check Release

on:
  pull_request:
    branches:
      - 'release/**'
      - 'develop'

permissions:
  pull-requests: write

jobs:
  get-changed-files:
    name: Get Changed Files
    runs-on: ubuntu-latest
    outputs:
      any_flutter_whisper_kit_apple_changed: ${{ contains(steps.changed-files.outputs.all_changed_files, 'packages/flutter_whisper_kit_apple') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v10.1

  output-changed-files:
    name: Output Changed Files
    needs: get-changed-files
    runs-on: ubuntu-latest
    steps:
      - name: Output Changed Files Info
        run: |
          echo "Changed files in flutter_whisper_kit_apple: ${{ needs.get-changed-files.outputs.any_flutter_whisper_kit_apple_changed }}"

  validate-apple-package-versions:
    name: Validate Apple Package Versions
    needs: get-changed-files
    if: ${{ needs.get-changed-files.outputs.any_flutter_whisper_kit_apple_changed == 'true' }}
    uses: ./.github/workflows/wc-version-validation.yml
    with:
      pubspec_path: packages/flutter_whisper_kit_apple/pubspec.yaml
      podspec_path: packages/flutter_whisper_kit_apple/darwin/flutter_whisper_kit_apple.podspec

  sdk-compatibility:
    name: Run SDK Compatibility Tests
    uses: ./.github/workflows/wc-sdk-compatibility.yml
