name: SDK Compatibility Tests

on:
  pull_request:
    branches:
      - 'release/**'
  workflow_dispatch:

jobs:
  sdk-compatibility:
    name: Run SDK Compatibility Tests
    uses: ./.github/workflows/wc-sdk-compatibility.yml
